services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
    container_name: news-aggregator-api
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=news_aggregator
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=3306
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=news_aggregator
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
